name: version_checker_example
description: Demonstrates how to use the version_checker package.

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  version_checker:
    path: ../

flutter:
  uses-material-design: true
