name: version_checker
version: 1.5.0
homepage: https://github.com/marchdev-tk/version_checker
description: Version Checker Popup is used to prompt user for website reloading with clearing cached data to apply a new version of the site.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  package_info: ^2.0.0
  pub_semver: ^2.0.0
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/env.json
